version: '3'
services:
  ctfd-release-time-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - ctfd-release-time-network

networks:
  ctfd-release-time-network:
    driver: bridge
